// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"log"

	"digidrop/ent/migrate"

	"digidrop/ent/filemiddleware"
	"digidrop/ent/user"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// FileMiddleware is the client for interacting with the FileMiddleware builders.
	FileMiddleware *FileMiddlewareClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.FileMiddleware = NewFileMiddlewareClient(c.config)
	c.User = NewUserClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		FileMiddleware: NewFileMiddlewareClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		FileMiddleware: NewFileMiddlewareClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		FileMiddleware.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.FileMiddleware.Use(hooks...)
	c.User.Use(hooks...)
}

// FileMiddlewareClient is a client for the FileMiddleware schema.
type FileMiddlewareClient struct {
	config
}

// NewFileMiddlewareClient returns a client for the FileMiddleware from the given config.
func NewFileMiddlewareClient(c config) *FileMiddlewareClient {
	return &FileMiddlewareClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `filemiddleware.Hooks(f(g(h())))`.
func (c *FileMiddlewareClient) Use(hooks ...Hook) {
	c.hooks.FileMiddleware = append(c.hooks.FileMiddleware, hooks...)
}

// Create returns a create builder for FileMiddleware.
func (c *FileMiddlewareClient) Create() *FileMiddlewareCreate {
	mutation := newFileMiddlewareMutation(c.config, OpCreate)
	return &FileMiddlewareCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FileMiddleware entities.
func (c *FileMiddlewareClient) CreateBulk(builders ...*FileMiddlewareCreate) *FileMiddlewareCreateBulk {
	return &FileMiddlewareCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FileMiddleware.
func (c *FileMiddlewareClient) Update() *FileMiddlewareUpdate {
	mutation := newFileMiddlewareMutation(c.config, OpUpdate)
	return &FileMiddlewareUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FileMiddlewareClient) UpdateOne(fm *FileMiddleware) *FileMiddlewareUpdateOne {
	mutation := newFileMiddlewareMutation(c.config, OpUpdateOne, withFileMiddleware(fm))
	return &FileMiddlewareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FileMiddlewareClient) UpdateOneID(id uuid.UUID) *FileMiddlewareUpdateOne {
	mutation := newFileMiddlewareMutation(c.config, OpUpdateOne, withFileMiddlewareID(id))
	return &FileMiddlewareUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FileMiddleware.
func (c *FileMiddlewareClient) Delete() *FileMiddlewareDelete {
	mutation := newFileMiddlewareMutation(c.config, OpDelete)
	return &FileMiddlewareDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *FileMiddlewareClient) DeleteOne(fm *FileMiddleware) *FileMiddlewareDeleteOne {
	return c.DeleteOneID(fm.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *FileMiddlewareClient) DeleteOneID(id uuid.UUID) *FileMiddlewareDeleteOne {
	builder := c.Delete().Where(filemiddleware.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FileMiddlewareDeleteOne{builder}
}

// Query returns a query builder for FileMiddleware.
func (c *FileMiddlewareClient) Query() *FileMiddlewareQuery {
	return &FileMiddlewareQuery{
		config: c.config,
	}
}

// Get returns a FileMiddleware entity by its id.
func (c *FileMiddlewareClient) Get(ctx context.Context, id uuid.UUID) (*FileMiddleware, error) {
	return c.Query().Where(filemiddleware.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FileMiddlewareClient) GetX(ctx context.Context, id uuid.UUID) *FileMiddleware {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFileMiddlewareToUser queries the FileMiddlewareToUser edge of a FileMiddleware.
func (c *FileMiddlewareClient) QueryFileMiddlewareToUser(fm *FileMiddleware) *UserQuery {
	query := &UserQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := fm.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(filemiddleware.Table, filemiddleware.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, filemiddleware.FileMiddlewareToUserTable, filemiddleware.FileMiddlewareToUserColumn),
		)
		fromV = sqlgraph.Neighbors(fm.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FileMiddlewareClient) Hooks() []Hook {
	return c.hooks.FileMiddleware
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Create returns a create builder for User.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uuid.UUID) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *UserClient) DeleteOneID(id uuid.UUID) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uuid.UUID) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uuid.UUID) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUserFromFileMiddleware queries the UserFromFileMiddleware edge of a User.
func (c *UserClient) QueryUserFromFileMiddleware(u *User) *FileMiddlewareQuery {
	query := &FileMiddlewareQuery{config: c.config}
	query.path = func(ctx context.Context) (fromV *sql.Selector, _ error) {
		id := u.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(user.Table, user.FieldID, id),
			sqlgraph.To(filemiddleware.Table, filemiddleware.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, user.UserFromFileMiddlewareTable, user.UserFromFileMiddlewareColumn),
		)
		fromV = sqlgraph.Neighbors(u.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}
