// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"digidrop/ent/filemiddleware"
	"digidrop/ent/predicate"
	"digidrop/ent/user"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FileMiddlewareQuery is the builder for querying FileMiddleware entities.
type FileMiddlewareQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.FileMiddleware
	// eager-loading edges.
	withFileMiddlewareToUser *UserQuery
	withFKs                  bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FileMiddlewareQuery builder.
func (fmq *FileMiddlewareQuery) Where(ps ...predicate.FileMiddleware) *FileMiddlewareQuery {
	fmq.predicates = append(fmq.predicates, ps...)
	return fmq
}

// Limit adds a limit step to the query.
func (fmq *FileMiddlewareQuery) Limit(limit int) *FileMiddlewareQuery {
	fmq.limit = &limit
	return fmq
}

// Offset adds an offset step to the query.
func (fmq *FileMiddlewareQuery) Offset(offset int) *FileMiddlewareQuery {
	fmq.offset = &offset
	return fmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fmq *FileMiddlewareQuery) Unique(unique bool) *FileMiddlewareQuery {
	fmq.unique = &unique
	return fmq
}

// Order adds an order step to the query.
func (fmq *FileMiddlewareQuery) Order(o ...OrderFunc) *FileMiddlewareQuery {
	fmq.order = append(fmq.order, o...)
	return fmq
}

// QueryFileMiddlewareToUser chains the current query on the "FileMiddlewareToUser" edge.
func (fmq *FileMiddlewareQuery) QueryFileMiddlewareToUser() *UserQuery {
	query := &UserQuery{config: fmq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(filemiddleware.Table, filemiddleware.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, filemiddleware.FileMiddlewareToUserTable, filemiddleware.FileMiddlewareToUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(fmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FileMiddleware entity from the query.
// Returns a *NotFoundError when no FileMiddleware was found.
func (fmq *FileMiddlewareQuery) First(ctx context.Context) (*FileMiddleware, error) {
	nodes, err := fmq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{filemiddleware.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fmq *FileMiddlewareQuery) FirstX(ctx context.Context) *FileMiddleware {
	node, err := fmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FileMiddleware ID from the query.
// Returns a *NotFoundError when no FileMiddleware ID was found.
func (fmq *FileMiddlewareQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = fmq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{filemiddleware.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fmq *FileMiddlewareQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := fmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FileMiddleware entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one FileMiddleware entity is not found.
// Returns a *NotFoundError when no FileMiddleware entities are found.
func (fmq *FileMiddlewareQuery) Only(ctx context.Context) (*FileMiddleware, error) {
	nodes, err := fmq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{filemiddleware.Label}
	default:
		return nil, &NotSingularError{filemiddleware.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fmq *FileMiddlewareQuery) OnlyX(ctx context.Context) *FileMiddleware {
	node, err := fmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FileMiddleware ID in the query.
// Returns a *NotSingularError when exactly one FileMiddleware ID is not found.
// Returns a *NotFoundError when no entities are found.
func (fmq *FileMiddlewareQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = fmq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{filemiddleware.Label}
	default:
		err = &NotSingularError{filemiddleware.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fmq *FileMiddlewareQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := fmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FileMiddlewares.
func (fmq *FileMiddlewareQuery) All(ctx context.Context) ([]*FileMiddleware, error) {
	if err := fmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return fmq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (fmq *FileMiddlewareQuery) AllX(ctx context.Context) []*FileMiddleware {
	nodes, err := fmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FileMiddleware IDs.
func (fmq *FileMiddlewareQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := fmq.Select(filemiddleware.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fmq *FileMiddlewareQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := fmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fmq *FileMiddlewareQuery) Count(ctx context.Context) (int, error) {
	if err := fmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return fmq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (fmq *FileMiddlewareQuery) CountX(ctx context.Context) int {
	count, err := fmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fmq *FileMiddlewareQuery) Exist(ctx context.Context) (bool, error) {
	if err := fmq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return fmq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (fmq *FileMiddlewareQuery) ExistX(ctx context.Context) bool {
	exist, err := fmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FileMiddlewareQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fmq *FileMiddlewareQuery) Clone() *FileMiddlewareQuery {
	if fmq == nil {
		return nil
	}
	return &FileMiddlewareQuery{
		config:                   fmq.config,
		limit:                    fmq.limit,
		offset:                   fmq.offset,
		order:                    append([]OrderFunc{}, fmq.order...),
		predicates:               append([]predicate.FileMiddleware{}, fmq.predicates...),
		withFileMiddlewareToUser: fmq.withFileMiddlewareToUser.Clone(),
		// clone intermediate query.
		sql:  fmq.sql.Clone(),
		path: fmq.path,
	}
}

// WithFileMiddlewareToUser tells the query-builder to eager-load the nodes that are connected to
// the "FileMiddlewareToUser" edge. The optional arguments are used to configure the query builder of the edge.
func (fmq *FileMiddlewareQuery) WithFileMiddlewareToUser(opts ...func(*UserQuery)) *FileMiddlewareQuery {
	query := &UserQuery{config: fmq.config}
	for _, opt := range opts {
		opt(query)
	}
	fmq.withFileMiddlewareToUser = query
	return fmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		URLID string `json:"url_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FileMiddleware.Query().
//		GroupBy(filemiddleware.FieldURLID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (fmq *FileMiddlewareQuery) GroupBy(field string, fields ...string) *FileMiddlewareGroupBy {
	group := &FileMiddlewareGroupBy{config: fmq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := fmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return fmq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		URLID string `json:"url_id,omitempty"`
//	}
//
//	client.FileMiddleware.Query().
//		Select(filemiddleware.FieldURLID).
//		Scan(ctx, &v)
//
func (fmq *FileMiddlewareQuery) Select(fields ...string) *FileMiddlewareSelect {
	fmq.fields = append(fmq.fields, fields...)
	return &FileMiddlewareSelect{FileMiddlewareQuery: fmq}
}

func (fmq *FileMiddlewareQuery) prepareQuery(ctx context.Context) error {
	for _, f := range fmq.fields {
		if !filemiddleware.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fmq.path != nil {
		prev, err := fmq.path(ctx)
		if err != nil {
			return err
		}
		fmq.sql = prev
	}
	return nil
}

func (fmq *FileMiddlewareQuery) sqlAll(ctx context.Context) ([]*FileMiddleware, error) {
	var (
		nodes       = []*FileMiddleware{}
		withFKs     = fmq.withFKs
		_spec       = fmq.querySpec()
		loadedTypes = [1]bool{
			fmq.withFileMiddlewareToUser != nil,
		}
	)
	if fmq.withFileMiddlewareToUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, filemiddleware.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &FileMiddleware{config: fmq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, fmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := fmq.withFileMiddlewareToUser; query != nil {
		ids := make([]uuid.UUID, 0, len(nodes))
		nodeids := make(map[uuid.UUID][]*FileMiddleware)
		for i := range nodes {
			if nodes[i].file_middleware_file_middleware_to_user == nil {
				continue
			}
			fk := *nodes[i].file_middleware_file_middleware_to_user
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "file_middleware_file_middleware_to_user" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.FileMiddlewareToUser = n
			}
		}
	}

	return nodes, nil
}

func (fmq *FileMiddlewareQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fmq.querySpec()
	_spec.Node.Columns = fmq.fields
	if len(fmq.fields) > 0 {
		_spec.Unique = fmq.unique != nil && *fmq.unique
	}
	return sqlgraph.CountNodes(ctx, fmq.driver, _spec)
}

func (fmq *FileMiddlewareQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := fmq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (fmq *FileMiddlewareQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   filemiddleware.Table,
			Columns: filemiddleware.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: filemiddleware.FieldID,
			},
		},
		From:   fmq.sql,
		Unique: true,
	}
	if unique := fmq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := fmq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, filemiddleware.FieldID)
		for i := range fields {
			if fields[i] != filemiddleware.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fmq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fmq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fmq *FileMiddlewareQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fmq.driver.Dialect())
	t1 := builder.Table(filemiddleware.Table)
	columns := fmq.fields
	if len(columns) == 0 {
		columns = filemiddleware.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fmq.sql != nil {
		selector = fmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fmq.unique != nil && *fmq.unique {
		selector.Distinct()
	}
	for _, p := range fmq.predicates {
		p(selector)
	}
	for _, p := range fmq.order {
		p(selector)
	}
	if offset := fmq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fmq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FileMiddlewareGroupBy is the group-by builder for FileMiddleware entities.
type FileMiddlewareGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fmgb *FileMiddlewareGroupBy) Aggregate(fns ...AggregateFunc) *FileMiddlewareGroupBy {
	fmgb.fns = append(fmgb.fns, fns...)
	return fmgb
}

// Scan applies the group-by query and scans the result into the given value.
func (fmgb *FileMiddlewareGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := fmgb.path(ctx)
	if err != nil {
		return err
	}
	fmgb.sql = query
	return fmgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (fmgb *FileMiddlewareGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := fmgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (fmgb *FileMiddlewareGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(fmgb.fields) > 1 {
		return nil, errors.New("ent: FileMiddlewareGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := fmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (fmgb *FileMiddlewareGroupBy) StringsX(ctx context.Context) []string {
	v, err := fmgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (fmgb *FileMiddlewareGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = fmgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filemiddleware.Label}
	default:
		err = fmt.Errorf("ent: FileMiddlewareGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (fmgb *FileMiddlewareGroupBy) StringX(ctx context.Context) string {
	v, err := fmgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (fmgb *FileMiddlewareGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(fmgb.fields) > 1 {
		return nil, errors.New("ent: FileMiddlewareGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := fmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (fmgb *FileMiddlewareGroupBy) IntsX(ctx context.Context) []int {
	v, err := fmgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (fmgb *FileMiddlewareGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = fmgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filemiddleware.Label}
	default:
		err = fmt.Errorf("ent: FileMiddlewareGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (fmgb *FileMiddlewareGroupBy) IntX(ctx context.Context) int {
	v, err := fmgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (fmgb *FileMiddlewareGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(fmgb.fields) > 1 {
		return nil, errors.New("ent: FileMiddlewareGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := fmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (fmgb *FileMiddlewareGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := fmgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (fmgb *FileMiddlewareGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = fmgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filemiddleware.Label}
	default:
		err = fmt.Errorf("ent: FileMiddlewareGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (fmgb *FileMiddlewareGroupBy) Float64X(ctx context.Context) float64 {
	v, err := fmgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (fmgb *FileMiddlewareGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(fmgb.fields) > 1 {
		return nil, errors.New("ent: FileMiddlewareGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := fmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (fmgb *FileMiddlewareGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := fmgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (fmgb *FileMiddlewareGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = fmgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filemiddleware.Label}
	default:
		err = fmt.Errorf("ent: FileMiddlewareGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (fmgb *FileMiddlewareGroupBy) BoolX(ctx context.Context) bool {
	v, err := fmgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (fmgb *FileMiddlewareGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range fmgb.fields {
		if !filemiddleware.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := fmgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fmgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (fmgb *FileMiddlewareGroupBy) sqlQuery() *sql.Selector {
	selector := fmgb.sql.Select()
	aggregation := make([]string, 0, len(fmgb.fns))
	for _, fn := range fmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(fmgb.fields)+len(fmgb.fns))
		for _, f := range fmgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(fmgb.fields...)...)
}

// FileMiddlewareSelect is the builder for selecting fields of FileMiddleware entities.
type FileMiddlewareSelect struct {
	*FileMiddlewareQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (fms *FileMiddlewareSelect) Scan(ctx context.Context, v interface{}) error {
	if err := fms.prepareQuery(ctx); err != nil {
		return err
	}
	fms.sql = fms.FileMiddlewareQuery.sqlQuery(ctx)
	return fms.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (fms *FileMiddlewareSelect) ScanX(ctx context.Context, v interface{}) {
	if err := fms.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (fms *FileMiddlewareSelect) Strings(ctx context.Context) ([]string, error) {
	if len(fms.fields) > 1 {
		return nil, errors.New("ent: FileMiddlewareSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := fms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (fms *FileMiddlewareSelect) StringsX(ctx context.Context) []string {
	v, err := fms.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (fms *FileMiddlewareSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = fms.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filemiddleware.Label}
	default:
		err = fmt.Errorf("ent: FileMiddlewareSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (fms *FileMiddlewareSelect) StringX(ctx context.Context) string {
	v, err := fms.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (fms *FileMiddlewareSelect) Ints(ctx context.Context) ([]int, error) {
	if len(fms.fields) > 1 {
		return nil, errors.New("ent: FileMiddlewareSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := fms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (fms *FileMiddlewareSelect) IntsX(ctx context.Context) []int {
	v, err := fms.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (fms *FileMiddlewareSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = fms.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filemiddleware.Label}
	default:
		err = fmt.Errorf("ent: FileMiddlewareSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (fms *FileMiddlewareSelect) IntX(ctx context.Context) int {
	v, err := fms.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (fms *FileMiddlewareSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(fms.fields) > 1 {
		return nil, errors.New("ent: FileMiddlewareSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := fms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (fms *FileMiddlewareSelect) Float64sX(ctx context.Context) []float64 {
	v, err := fms.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (fms *FileMiddlewareSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = fms.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filemiddleware.Label}
	default:
		err = fmt.Errorf("ent: FileMiddlewareSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (fms *FileMiddlewareSelect) Float64X(ctx context.Context) float64 {
	v, err := fms.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (fms *FileMiddlewareSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(fms.fields) > 1 {
		return nil, errors.New("ent: FileMiddlewareSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := fms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (fms *FileMiddlewareSelect) BoolsX(ctx context.Context) []bool {
	v, err := fms.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (fms *FileMiddlewareSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = fms.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{filemiddleware.Label}
	default:
		err = fmt.Errorf("ent: FileMiddlewareSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (fms *FileMiddlewareSelect) BoolX(ctx context.Context) bool {
	v, err := fms.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (fms *FileMiddlewareSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := fms.sql.Query()
	if err := fms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
