// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"digidrop/ent/filemiddleware"
	"digidrop/ent/predicate"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileMiddlewareDelete is the builder for deleting a FileMiddleware entity.
type FileMiddlewareDelete struct {
	config
	hooks    []Hook
	mutation *FileMiddlewareMutation
}

// Where appends a list predicates to the FileMiddlewareDelete builder.
func (fmd *FileMiddlewareDelete) Where(ps ...predicate.FileMiddleware) *FileMiddlewareDelete {
	fmd.mutation.Where(ps...)
	return fmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fmd *FileMiddlewareDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(fmd.hooks) == 0 {
		affected, err = fmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FileMiddlewareMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fmd.mutation = mutation
			affected, err = fmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fmd.hooks) - 1; i >= 0; i-- {
			if fmd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (fmd *FileMiddlewareDelete) ExecX(ctx context.Context) int {
	n, err := fmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fmd *FileMiddlewareDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: filemiddleware.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: filemiddleware.FieldID,
			},
		},
	}
	if ps := fmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, fmd.driver, _spec)
}

// FileMiddlewareDeleteOne is the builder for deleting a single FileMiddleware entity.
type FileMiddlewareDeleteOne struct {
	fmd *FileMiddlewareDelete
}

// Exec executes the deletion query.
func (fmdo *FileMiddlewareDeleteOne) Exec(ctx context.Context) error {
	n, err := fmdo.fmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{filemiddleware.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fmdo *FileMiddlewareDeleteOne) ExecX(ctx context.Context) {
	fmdo.fmd.ExecX(ctx)
}
