// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (fm *FileMiddleware) FileMiddlewareToUser(ctx context.Context) (*User, error) {
	result, err := fm.Edges.FileMiddlewareToUserOrErr()
	if IsNotLoaded(err) {
		result, err = fm.QueryFileMiddlewareToUser().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (u *User) UserFromFileMiddleware(ctx context.Context) ([]*FileMiddleware, error) {
	result, err := u.Edges.UserFromFileMiddlewareOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryUserFromFileMiddleware().All(ctx)
	}
	return result, err
}
