// Code generated by entc, DO NOT EDIT.

package ent

import (
	"digidrop/ent/filemiddleware"
	"digidrop/ent/schema"
	"digidrop/ent/user"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	filemiddlewareFields := schema.FileMiddleware{}.Fields()
	_ = filemiddlewareFields
	// filemiddlewareDescAccessed is the schema descriptor for accessed field.
	filemiddlewareDescAccessed := filemiddlewareFields[3].Descriptor()
	// filemiddleware.DefaultAccessed holds the default value on creation for the accessed field.
	filemiddleware.DefaultAccessed = filemiddlewareDescAccessed.Default.(bool)
	// filemiddlewareDescID is the schema descriptor for id field.
	filemiddlewareDescID := filemiddlewareFields[0].Descriptor()
	// filemiddleware.DefaultID holds the default value on creation for the id field.
	filemiddleware.DefaultID = filemiddlewareDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
