// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FileMiddleware is the predicate function for filemiddleware builders.
type FileMiddleware func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
